const FETCH_CURRENT_USER_BEGIN = 'FETCH_CURRENT_USER_BEGIN';
const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
const FETCH_CURRENT_USER_FAILURE = 'FETCH_CURRENT_USER_FAILURE';
const FETCH_FAVORITE_PHOTOS_SUCCESS = 'FETCH_FAVORITE_PHOTOS_SUCCESS';
const FETCH_FAVORITE_USERS_SUCCESS = 'FETCH_FAVORITE_USERS_SUCCESS';
const FETCH_UPLOADED_PHOTOS_SUCCESS = 'FETCH_UPLOADED_PHOTOS_SUCCESS';

export default {
  FETCH_CURRENT_USER_BEGIN,
  FETCH_CURRENT_USER_SUCCESS,
  FETCH_CURRENT_USER_FAILURE,
  FETCH_FAVORITE_PHOTOS_SUCCESS,
  FETCH_FAVORITE_USERS_SUCCESS,
  FETCH_UPLOADED_PHOTOS_SUCCESS
}
