const SET_ACTIVE_PHOTO_CATEGORY = 'SET_ACTIVE_PHOTO_CATEGORY';

const FETCH_PHOTOS_BEGIN = 'FETCH_PHOTOS_BEGIN';
const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
const FETCH_PHOTOS_FAILURE = 'FETCH_PHOTOS_FAILURE';

const FETCH_PHOTO_CATEGORIES_BEGIN = 'FETCH_PHOTO_CATEGORIES_BEGIN';
const FETCH_PHOTO_CATEGORIES_SUCCESS = 'FETCH_PHOTO_CATEGORIES_SUCCESS';
const FETCH_PHOTO_CATEGORIES_FAILURE = 'FETCH_PHOTO_CATEGORIES_FAILURE';

export default {
  SET_ACTIVE_PHOTO_CATEGORY,
  FETCH_PHOTOS_BEGIN,
  FETCH_PHOTOS_SUCCESS,
  FETCH_PHOTOS_FAILURE,
  FETCH_PHOTO_CATEGORIES_BEGIN,
  FETCH_PHOTO_CATEGORIES_SUCCESS,
  FETCH_PHOTO_CATEGORIES_FAILURE
}
