const FETCH_AUTHORS_BEGIN = 'FETCH_AUTHORS_BEGIN';
const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
const FETCH_AUTHORS_FAILURE = 'FETCH_AUTHORS_FAILURE';

export default {
  FETCH_AUTHORS_BEGIN,
  FETCH_AUTHORS_SUCCESS,
  FETCH_AUTHORS_FAILURE
}
